---
- name: Ensure pip3 is installed on Ubuntu/Debian
  ansible.builtin.package:
    name: python3-pip
    state: present
  become: true

- name: Get Service Facts
  ansible.builtin.service_facts:

- name: systemd-resolved tasks
  block:
    - name: Ensure DNS Stub is disabled for systemd-resolved on Ubuntu
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: "^#DNSStubListener=yes"
        line: "DNSStubListener=no"
      become: true

    - name: Ensure /etc/resolved.conf points to the correct file
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: true
      notify: Restart systemd-resolved
      become: true
  when: ansible_facts['services']['systemd-resolved.service']['status'] | default('not-found') != 'not-found'
